FROM ubuntu:latest
LABEL maintainer="johnny@whistlebird.co.nz"

# Set timezone
RUN ln -snf /usr/share/zoneinfo/Pacific/Auckland /etc/localtime && echo Pacific/Auckland > /etc/timezone

# Update and install Python
RUN apt-get -y update && apt-get install -y python3 python3-pip

# Set working directory
WORKDIR /app

# Copy application files
COPY . .

# Install Python dependencies
RUN pip3 install -r requirements.txt

# Expose port
EXPOSE 80

# Set environment variable
ENV WB_ENVIRONMENT=test

# Run the application
CMD ["python3", "app.py"]
