"""Replayable disposal of expired raw-material stock for Whistlebird Ltd.

Expired stock left on the shelf should be written off, not sit in inventory as if it were usable.
`docs/whistlebird-disposals-source.json` lists each lot to dispose of; this module replays them
through the real wastage API (`POST /api/core/inventory/wastage`) after the Core history, the same
route and validation the "Dispose" page hits. The API stamps "now", so the timestamp pass
(`whistlebird_replay_correct_timestamps.py`) then sets each disposal's recorded date.

The list is generated by `scripts/whistlebird_replay_simulation.py plan --write`. Each entry
carries the quantity the replay expects to find in the lot; if the replayed lot holds anything
else the allocation has drifted from the manifest, and the replay stops rather than dispose a
different amount than was curated.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from datetime import date
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo

DEFAULT_DISPOSALS_MANIFEST = Path(__file__).parents[1] / "docs" / "whistlebird-disposals-source.json"

_MANIFEST_KEYS = {"_comment", "disposals"}
_DISPOSAL_KEYS = {"lot", "ingredient", "quantity", "unit", "date", "reason"}
_LOT_MARKER = re.compile(r"^raw-[A-Za-z0-9._-]+$")
_MAX_REASON = 500
# The timezone whistlebird_migration._derived_timestamp stamps business dates in (noon local).
_LOCAL_TZ = ZoneInfo("Pacific/Auckland")


class DisposalManifestError(ValueError):
    """The disposals manifest is malformed. Raised before any request is issued."""


class DisposalReplayError(RuntimeError):
    """A disposal cannot be replayed as curated (lot missing, or holding a different quantity)."""


@dataclass(frozen=True)
class Disposal:
    lot: str
    ingredient: str
    quantity: Decimal
    unit: str
    on: date
    reason: str

    def idempotency_key(self) -> str:
        return f"whistlebird-disposal:{self.lot}"


def _decimal(value: Any, where: str) -> Decimal:
    try:
        parsed = Decimal(str(value))
    except (InvalidOperation, ValueError) as exc:
        raise DisposalManifestError(f"{where}: quantity must be a number") from exc
    if not parsed.is_finite() or parsed <= 0:
        raise DisposalManifestError(f"{where}: quantity must be positive")
    return parsed


def parse_disposals_manifest(data: dict[str, Any]) -> tuple[Disposal, ...]:
    if not isinstance(data, dict):
        raise DisposalManifestError("manifest must be a JSON object")
    unknown = sorted(set(data) - _MANIFEST_KEYS)
    if unknown:
        raise DisposalManifestError(f"manifest: unknown key(s) {unknown}")
    raw = data.get("disposals")
    if not isinstance(raw, list):
        raise DisposalManifestError("manifest: disposals must be a list")

    disposals: list[Disposal] = []
    for index, entry in enumerate(raw):
        where = f"disposals[{index}]"
        if not isinstance(entry, dict):
            raise DisposalManifestError(f"{where}: must be an object")
        unknown = sorted(set(entry) - _DISPOSAL_KEYS)
        if unknown:
            raise DisposalManifestError(f"{where}: unknown key(s) {unknown}")
        missing = sorted(_DISPOSAL_KEYS - set(entry))
        if missing:
            raise DisposalManifestError(f"{where}: missing {missing}")
        lot = str(entry["lot"])
        if not _LOT_MARKER.match(lot):
            raise DisposalManifestError(f"{where}: lot must be a raw-material import marker (raw-...)")
        reason = str(entry["reason"]).replace("\x00", "").strip()
        if not reason:
            raise DisposalManifestError(f"{where}: reason is required")
        if len(reason) > _MAX_REASON:
            raise DisposalManifestError(f"{where}: reason must be {_MAX_REASON} characters or fewer")
        try:
            on = date.fromisoformat(str(entry["date"]))
        except ValueError as exc:
            raise DisposalManifestError(f"{where}: date must be an ISO date") from exc
        unit = str(entry["unit"]).strip()
        if not unit:
            raise DisposalManifestError(f"{where}: unit is required")
        disposals.append(
            Disposal(
                lot=lot,
                ingredient=str(entry["ingredient"]),
                quantity=_decimal(entry["quantity"], where),
                unit=unit,
                on=on,
                reason=reason,
            )
        )
    lots = [d.lot for d in disposals]
    duplicates = sorted({lot for lot in lots if lots.count(lot) > 1})
    if duplicates:
        raise DisposalManifestError(f"disposals: duplicate lot(s) {duplicates}")
    return tuple(disposals)


def load_disposals_manifest(path: Path = DEFAULT_DISPOSALS_MANIFEST) -> tuple[Disposal, ...]:
    try:
        data = json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise DisposalManifestError(f"cannot read disposals manifest {path}: {exc}") from exc
    return parse_disposals_manifest(data)


def replay_disposals(client: Any, store: Any, disposals: tuple[Disposal, ...]) -> dict[str, int]:
    """Dispose of each listed lot through the real wastage API. Resumable: a lot that already has a
    wastage record is skipped. Runs after every Core event, so all consumption has already happened."""
    counts = {"disposed": 0, "skipped": 0}
    for disposal in disposals:
        lot = store.raw_material_for_marker(disposal.lot)
        if lot is None:
            raise DisposalReplayError(f"{disposal.lot}: no such lot in the target")
        if store.wastage_recorded_for_item(lot["id"]):
            counts["skipped"] += 1
            continue
        if lot["unit"] != disposal.unit:
            raise DisposalReplayError(f"{disposal.lot}: unit is {lot['unit']!r}, manifest says {disposal.unit!r}")
        held = Decimal(str(lot["quantity"]))
        if held != disposal.quantity:
            raise DisposalReplayError(
                f"{disposal.lot} ({disposal.ingredient}) holds {held} {lot['unit']} but the manifest expects "
                f"{disposal.quantity}: the replay's allocation has drifted from docs/whistlebird-disposals-source.json "
                "(re-run `scripts/whistlebird_replay_simulation.py plan --write`)"
            )
        response = client.post(
            "/api/core/inventory/wastage",
            {
                "entries": [
                    {
                        "inventory_item_id": str(lot["id"]),
                        "quantity_wasted": str(disposal.quantity),
                        "quantity_unit": disposal.unit,
                        "reason": disposal.reason,
                    }
                ],
                "idempotency_key": disposal.idempotency_key(),
            },
        )
        if response.get("success") is False:
            raise DisposalReplayError(f"{disposal.lot}: wastage API refused: {response}")
        counts["disposed"] += 1
    return counts


# --- timestamps and verification (target database) -----------------------------------------


def _org_id(conn: Any, org_name: str) -> Any:
    from sqlalchemy import text

    org_id = conn.execute(text("SELECT id FROM organisations WHERE name = :name"), {"name": org_name}).scalar()
    if org_id is None:
        raise DisposalReplayError(f"organisation {org_name!r} does not exist")
    return org_id


def correct_disposal_timestamps(
    target_url: str, org_name: str, disposals: tuple[Disposal, ...], business_at: Any
) -> int:
    """Set each disposal's recorded date (and its ledger line's) to the manifest date.

    `business_at(date) -> datetime` is the noon-local convention the rest of the timestamp pass uses.
    Internal tooling for a demo/test tenant only; the live app has no way to backdate a disposal.
    """
    from sqlalchemy import create_engine, text

    engine = create_engine(target_url)
    corrected = 0
    try:
        with engine.begin() as conn:
            org_id = _org_id(conn, org_name)
            for disposal in disposals:
                at = business_at(disposal.on)
                params = {"org_id": org_id, "marker": disposal.lot, "at": at}
                conn.execute(
                    text(
                        "UPDATE inventory_movements SET created_at = :at WHERE org_id = :org_id "
                        "AND source_wastage_id IN (SELECT w.id FROM inventory_wastage w "
                        "JOIN inventory_items i ON i.id = w.inventory_item_id "
                        "WHERE w.org_id = :org_id AND i.extra_data->>'import_ref' = :marker)"
                    ),
                    params,
                )
                result = conn.execute(
                    text(
                        "UPDATE inventory_wastage SET recorded_at = :at, created_at = :at WHERE org_id = :org_id "
                        "AND inventory_item_id IN (SELECT id FROM inventory_items "
                        "WHERE org_id = :org_id AND extra_data->>'import_ref' = :marker)"
                    ),
                    params,
                )
                corrected += result.rowcount
    finally:
        engine.dispose()
    return corrected


def verify_disposals(target_url: str, org_name: str, disposals: tuple[Disposal, ...]) -> dict[str, Any]:
    """Read-only checks, each reported as a count that should be zero:

    * `expired_lot_uses`: consumptions dated after the consumed lot's expiry -- the point of all this;
    * `disposals_missing`: manifest lots with no wastage record, or still holding stock;
    * `disposal_date_mismatches`: wastage recorded on a date other than the manifest's.
    """
    from sqlalchemy import create_engine, text

    engine = create_engine(target_url)
    try:
        with engine.connect() as conn:
            org_id = _org_id(conn, org_name)
            late = conn.execute(
                text(
                    "SELECT count(*) FROM execution_steps es "
                    "CROSS JOIN LATERAL jsonb_array_elements(CASE WHEN jsonb_typeof(es.actual_inputs) = 'array' "
                    "THEN es.actual_inputs ELSE '[]'::jsonb END) AS inp "
                    "JOIN inventory_items i ON i.id = (inp->>'inventory_item_id')::uuid "
                    "WHERE es.org_id = :org_id AND es.completed_at IS NOT NULL "
                    "AND inp ? 'inventory_item_id' "
                    "AND i.expiry_date IS NOT NULL AND es.completed_at::date > i.expiry_date"
                ),
                {"org_id": org_id},
            ).scalar_one()
            missing = 0
            mismatched = 0
            for disposal in disposals:
                row = conn.execute(
                    text(
                        "SELECT i.quantity, "
                        "(SELECT w.recorded_at FROM inventory_wastage w WHERE w.inventory_item_id = i.id "
                        " ORDER BY w.created_at LIMIT 1) "
                        "FROM inventory_items i WHERE i.org_id = :org_id AND i.extra_data->>'import_ref' = :marker"
                    ),
                    {"org_id": org_id, "marker": disposal.lot},
                ).first()
                if row is None or row[1] is None or Decimal(str(row[0])) != 0:
                    missing += 1
                elif row[1].astimezone(_LOCAL_TZ).date() != disposal.on:
                    mismatched += 1
    finally:
        engine.dispose()
    return {
        "expired_lot_uses": {"expected": 0, "actual": late},
        "disposals_missing": {"expected": 0, "actual": missing},
        "disposal_date_mismatches": {"expected": 0, "actual": mismatched},
    }
