"""add 2fa fields to user

Revision ID: 926821db3a65
Revises: 0e781c27351d
Create Date: 2025-12-10 20:02:21.058701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '926821db3a65'
down_revision: Union[str, None] = '0e781c27351d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('two_factor_enabled', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'two_factor_enabled')
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###

