"""Monotonic seq cursor on entity_events for the /api/core/changes feed.

Revision ID: entity_events_seq_001
Revises: system_findings_cache_001

Adds a BIGINT GENERATED BY DEFAULT AS IDENTITY column. Postgres backfills existing rows
from the sequence in heap order -- historical ordering does not matter for a "what changed
recently" feed, only that new rows get a strictly increasing value. Plus a (org_id, seq)
index for the feed's keyset scan. Reversible (downgrade drops both).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "entity_events_seq_001"
down_revision: str | None = "system_findings_cache_001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | None = None


def upgrade() -> None:
    op.add_column(
        "entity_events",
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=False), nullable=False),
    )
    op.create_index("ix_entity_events_org_seq", "entity_events", ["org_id", "seq"])


def downgrade() -> None:
    op.drop_index("ix_entity_events_org_seq", table_name="entity_events")
    op.drop_column("entity_events", "seq")
