"""Drop the vestigial entity_events.seq IDENTITY and make (org_id, seq) UNIQUE.

Revision ID: entity_events_seq_noident_001
Revises: feat_subs_seq_merge_001

Background: the earlier commit-safe-cursor change (MR !205) made EventWriter.emit() the
sole allocator of entity_events.seq -- COALESCE(MAX(seq),0)+1 per org under a per-org
advisory lock held to commit. It KEPT the column's `GENERATED BY DEFAULT AS IDENTITY`
default and the changes-feed's 1-second `created_at` settle window as transitional belts
so a worker still on the previous release (which allocated seq from the bare global
sequence, no lock) could keep inserting during a rolling deploy.

*** DEPLOY PRECONDITION -- READ BEFORE APPLYING ***
This migration is only safe once NO worker is still relying on the IDENTITY default, i.e.
MR !205's code is fully rolled out to every worker. A pre-!205 worker's next
EventWriter.emit() would hit NOT NULL after this runs. This is NOT a rolling-deploy
migration -- gate it behind confirmation that the fleet is fully on >= !205.

What it does (index-only + one catalog-only column change; no row rewrite):

  1. `ALTER TABLE entity_events ALTER COLUMN seq DROP IDENTITY` -- removes the default so a
     write that bypasses EventWriter fails loudly on NOT NULL instead of silently taking a
     now-frozen sequence value.
  2. Replace the non-unique ix_entity_events_org_seq with a UNIQUE one so a
     double-allocation bug in _next_feed_seq fails loudly rather than corrupting feed
     order. Existing seq values are globally unique (old IDENTITY), so (org_id, seq) is
     already unique -- no data change. Built CONCURRENTLY under a temp name and swapped in
     by rename so entity_events (a hot, every-mutation-writes table) never loses its
     (org_id, seq) index. An interrupted CONCURRENTLY build leaves an indisvalid=false
     index; each build drops any invalid same-named leftover first.

The changes-feed settle window is removed in the same MR (dead weight -- seq is now
gap-free and commit-ordered for every writer).
"""

from collections.abc import Sequence

from alembic import op

revision: str = "entity_events_seq_noident_001"
down_revision: str | None = "feat_subs_seq_merge_001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | None = None

_TABLE = "entity_events"
_NAME = "ix_entity_events_org_seq"
_TMP_UP = "ix_entity_events_org_seq_uq"
_TMP_DOWN = "ix_entity_events_org_seq_ni"


def _drop_if_invalid(bind, name: str) -> None:
    from sqlalchemy import text

    invalid = bind.execute(
        text(
            "SELECT 1 FROM pg_class c JOIN pg_index i ON i.indexrelid = c.oid "
            "WHERE c.relname = :n AND NOT i.indisvalid"
        ),
        {"n": name},
    ).scalar()
    if invalid:
        op.drop_index(name, table_name=_TABLE, if_exists=True, postgresql_concurrently=True)


def _rename_index(old: str, new: str) -> None:
    # No alembic API for ALTER INDEX ... RENAME. `old`/`new` are module-level constants
    # (no caller input), so this is string concatenation of literals -- not an f-string,
    # and carries no injection surface.
    op.execute("ALTER INDEX " + old + " RENAME TO " + new)


def upgrade() -> None:
    with op.get_context().autocommit_block():
        op.execute("ALTER TABLE entity_events ALTER COLUMN seq DROP IDENTITY IF EXISTS")

        _drop_if_invalid(op.get_bind(), _TMP_UP)
        op.create_index(
            _TMP_UP, _TABLE, ["org_id", "seq"], unique=True, if_not_exists=True, postgresql_concurrently=True
        )
        op.drop_index(_NAME, table_name=_TABLE, if_exists=True, postgresql_concurrently=True)
        _rename_index(_TMP_UP, _NAME)


def downgrade() -> None:
    from sqlalchemy import text

    with op.get_context().autocommit_block():
        bind = op.get_bind()

        _drop_if_invalid(bind, _TMP_DOWN)
        op.create_index(
            _TMP_DOWN, _TABLE, ["org_id", "seq"], unique=False, if_not_exists=True, postgresql_concurrently=True
        )
        op.drop_index(_NAME, table_name=_TABLE, if_exists=True, postgresql_concurrently=True)
        _rename_index(_TMP_DOWN, _NAME)

        # Restartable: each statement in this autocommit block commits on its own, so a
        # retry after an interrupt must not re-issue ADD IDENTITY on a column that already
        # has one. Add it only when absent, then always (re)seed the sequence past MAX(seq).
        already_identity = bind.execute(
            text(
                "SELECT is_identity FROM information_schema.columns "
                "WHERE table_name = 'entity_events' AND column_name = 'seq'"
            )
        ).scalar()
        if already_identity != "YES":
            op.execute("ALTER TABLE entity_events ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY")
        op.execute(
            "SELECT setval(pg_get_serial_sequence('entity_events', 'seq'), "
            "COALESCE((SELECT MAX(seq) FROM entity_events), 1), true)"
        )
